(function(){'use strict';
const $=id=>document.getElementById(id),form=$('entryForm'),P=window.ReceiptParser;let originalFile=null,canvas=null,worker=null,busy=false,sending=false,docId=crypto.randomUUID(),angle=0;
const field=n=>form.elements.namedItem(n);function read(){return Object.fromEntries(['direction','person','date','document','invoice','expense','tax','total','payment','paymentDate','currency','item','advance','note'].map(k=>[k,field(k).value.trim()]));}
function message(id,s){$(id).textContent=s;}function dirty(){ $('checked').checked=false;message('sumStatus',P.validate(read()).filter(x=>/金額|總額|支出/.test(x)).join('；')); }
async function choose(file){if(!file)return;if(busy||sending){message('ocrStatus','請等目前辨識或送出完成再換照片。');return;}try{
 originalFile=file;const bytes=await file.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',bytes);docId='img-'+[...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join('');
 const url=URL.createObjectURL(file),im=new Image();try{im.src=url;await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject;});const ratio=Math.min(1,2400/Math.max(im.naturalWidth,im.naturalHeight));canvas=document.createElement('canvas');canvas.width=Math.round(im.naturalWidth*ratio);canvas.height=Math.round(im.naturalHeight*ratio);canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);$('photo').src=canvas.toDataURL('image/jpeg',0.9);$('photo').hidden=false;angle=0;}finally{URL.revokeObjectURL(url);}
 form.reset();syncDirection();field('currency').value='NTD';message('ocrStatus','照片已載入，請按「辨識照片」。');message('warnings','');message('sendStatus','');$('send').disabled=false;$('responseSection').hidden=true;
 }catch(e){message('ocrStatus','照片無法讀取，請改用 JPG／PNG 或重新拍照。');}}
['camera','gallery'].forEach(id=>$(id).addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';choose(file);}));
$('savePhoto').addEventListener('click',()=>{if(!originalFile){message('ocrStatus','目前沒有原照片。');return;}const url=URL.createObjectURL(originalFile),a=document.createElement('a');a.href=url;a.download=originalFile.name||'支出憑證照片.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('rotate').addEventListener('click',()=>{if(!canvas||busy)return;const next=document.createElement('canvas');next.width=canvas.height;next.height=canvas.width;const ctx=next.getContext('2d');ctx.translate(next.width/2,next.height/2);ctx.rotate(Math.PI/2);ctx.drawImage(canvas,-canvas.width/2,-canvas.height/2);canvas=next;angle=(angle+90)%360;$('photo').src=canvas.toDataURL('image/jpeg',0.9);dirty();});
function populate(raw){if(field('direction').value==='income'){message('warnings','收入採手動登錄；照片 OCR 僅用於支出。');return;}const r=P.parse(raw);for(const k of ['date','invoice','expense','tax','total','document'])if(r[k]!==undefined&&r[k]!==null)field(k).value=r[k];const applied=P.applyRules(raw,rules,read());for(const [k,v] of Object.entries(applied.values))field(k).value=v;field('invoice').disabled=field('document').value!=='invoice';dirty();message('warnings',[...r.warnings,...applied.warnings].join(' '));}
$('parseText').addEventListener('click',()=>populate($('ocrText').value));
$('recognize').addEventListener('click',async()=>{if(!canvas){message('ocrStatus','請先拍照或選照片。');return;}if(busy)return;busy=true;$('recognize').disabled=true;try{if(!window.Tesseract)throw Error('辨識程式尚未載入，請確認網路後重整');if(!worker)worker=await Tesseract.createWorker(['eng','chi_tra'],1,{logger:m=>message('ocrStatus',m.status==='recognizing text'?'辨識中 '+Math.round((m.progress||0)*100)+'%':'載入辨識模型中…')});const result=await worker.recognize(canvas);$('ocrText').value=result.data.text;populate(result.data.text);message('ocrStatus','辨識完成，請核對所有欄位。');}catch(e){message('ocrStatus','辨識未完成：'+e.message+'。仍可手動輸入後送出。');if(worker){await worker.terminate().catch(()=>{});worker=null;}}finally{busy=false;$('recognize').disabled=false;}});
field('document').addEventListener('change',()=>{field('invoice').disabled=field('document').value!=='invoice';if(field('document').value!=='receipt')field('noTaxReceipt').checked=false;dirty();});
field('noTaxReceipt').addEventListener('change',()=>{if(field('noTaxReceipt').checked){if(field('document').value!=='receipt'){field('noTaxReceipt').checked=false;message('warnings','只有確認為收據時才能選擇無稅收據。');return;}if(P.money(field('total').value)!==null){if(field('direction').value!=='income')field('expense').value=field('total').value;field('tax').value='0';}}dirty();});
form.addEventListener('input',e=>{if(e.target.id!=='checked')dirty();});form.addEventListener('change',e=>{if(e.target.id!=='checked')dirty();});
function ready(){const errors=P.validate(read());if(!form.reportValidity()||errors.length||!$('checked').checked){message('sendStatus',errors.join('；')||'請先核對並勾選確認');return false;}return true;}
form.addEventListener('submit',e=>{e.preventDefault();if(sending||!ready())return;sending=true;$('send').disabled=true;const data=P.payload(read(),docId),post=document.createElement('form');post.method='POST';post.action=P.FORM+'formResponse';post.target='googleResponse';data.forEach((value,key)=>{const input=document.createElement('input');input.type='hidden';input.name=key;input.value=value;post.appendChild(input);});document.body.appendChild(post);$('responseSection').hidden=false;post.submit();post.remove();message('sendStatus','已發出提交請求。請查看下方 Google 回覆，確認是否已記錄；不要因頁面載入就判定成功。');sending=false;});
$('confirmSent').addEventListener('click',()=>message('sendStatus','你已確認 Google 回覆。可清空新增下一筆；勿重送這張憑證。'));
$('retry').addEventListener('click',()=>{if(confirm('請先確認 Google 沒有記錄這筆回覆。確定要開放重送？')){$('send').disabled=false;message('sendStatus','已開放重送，請核對欄位後提交。憑證ID保持相同。');}});
$('prefill').addEventListener('click',()=>{if(ready())window.open(P.FORM+'viewform?usp=pp_url&'+P.payload(read(),docId).toString(),'_blank','noopener');});
$('newEntry').addEventListener('click',()=>{if(busy||sending)return;if(!confirm('清空目前欄位，新增下一筆？'))return;form.reset();syncDirection();canvas=null;originalFile=null;docId=crypto.randomUUID();$('photo').hidden=true;$('ocrText').value='';$('send').disabled=false;$('responseSection').hidden=true;['warnings','sumStatus','sendStatus'].forEach(id=>message(id,''));message('ocrStatus','請拍照或選照片。');});
$('export').addEventListener('click',()=>{if(!ready())return;const v=read(),payload=P.payload(v,docId);const headers=['時間戳記','業','日期','支出','稅','收入','收付訖','幣別','項目','發票','備註','代收墊'];const row=[new Date().toISOString(),...Object.keys(P.ENTRY).map(k=>payload.get('entry.'+P.ENTRY[k]))];const escape=s=>'"'+String(s??'').replace(/"/g,'""')+'"';const blob=new Blob(['\ufeff'+[headers,row].map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='收支登錄-'+v.date+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);message('sendStatus','已下載本筆 CSV，可直接匯入財務；Google 表單與 CSV 以相同憑證ID去重。');});

function syncDirection(){const income=field('direction').value==='income';$('expenseLabel').hidden=income;field('expense').required=!income;field('expense').disabled=income;field('payment').innerHTML=income?'<option value="">空白＝尚未收</option><option value="V">V＝收訖</option>':'<option value="">空白＝尚未付</option><option value="C">C＝付訖</option>';field('paymentDate').value='';field('invoice').disabled=field('document').value!=='invoice';dirty();}
field('direction').addEventListener('change',syncDirection);
const ruleKey='receipt-ocr-rules-v1',migrationKey='receipt-ocr-rules-defaults-164';
const defaults=[{keyword:'購買票品證明單',field:'item',value:'郵寄資費'},{keyword:'黑貓',field:'item',value:'宅配運費'},{keyword:'百康',field:'note',value:'百康'},{keyword:'蝦皮',field:'note',value:'蝦皮'}];let rules=defaults.map(r=>({...r}));
try{const stored=localStorage.getItem(ruleKey);if(stored)rules=checkRules(JSON.parse(stored));if(localStorage.getItem(migrationKey)!=='1'){for(const r of defaults)if(!rules.some(x=>x.keyword===r.keyword&&x.field===r.field))rules.push({...r});localStorage.setItem(ruleKey,JSON.stringify(rules));localStorage.setItem(migrationKey,'1');}}catch(e){message('ruleStatus','無法讀取或保存規則，請匯出備份；此頁仍可使用目前規則。');}
function checkRules(list){if(!Array.isArray(list)||list.length>500||list.some(r=>!r||typeof r.keyword!=='string'||!r.keyword.trim()||!['item','person','currency','note'].includes(r.field)||typeof r.value!=='string'||!r.value.trim()))throw Error('規則格式不正確');return list.map(r=>({keyword:r.keyword.trim(),field:r.field,value:r.value.trim()}));}
function renderRules(){const list=$('ruleList');list.replaceChildren();const names={item:'項目',person:'業',currency:'幣別',note:'備註'};rules.forEach((r,i)=>{const li=document.createElement('li');li.append(document.createTextNode(r.keyword+' → '+names[r.field]+'：'+r.value+' '));const button=document.createElement('button');button.type='button';button.textContent='刪除';button.onclick=()=>{rules.splice(i,1);saveRules();};li.append(button);list.append(li);});}
function saveRules(){try{localStorage.setItem(ruleKey,JSON.stringify(rules));message('ruleStatus','規則已保存。');}catch(e){message('ruleStatus','此瀏覽器無法保存，請立即匯出規則備份。');}renderRules();}
$('addRule').onclick=()=>{try{rules=checkRules([...rules,{keyword:$('ruleKeyword').value,field:$('ruleField').value,value:$('ruleValue').value}]);saveRules();$('ruleKeyword').value='';$('ruleValue').value='';}catch(e){message('ruleStatus',e.message);}};
$('exportRules').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(rules,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='ocr-rules.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
$('importRules').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{const next=checkRules(JSON.parse(await file.text()));if(!confirm('以匯入的規則取代目前規則？'))return;rules=next;saveRules();}catch(err){message('ruleStatus','匯入失敗：'+err.message);}};
renderRules();syncDirection();
})();
