(function(global){
'use strict';
const FORM='https://docs.google.com/forms/d/e/1FAIpQLSdgWlFhZCX03lXovKt7hJ2ovbx_bWE7jGqJ4dfguXR_L4AgqA/';
const ENTRY={person:'85528461',date:'110279927',expense:'1535940707',tax:'2094955144',income:'1138614808',payment:'1793926944',currency:'1491572199',item:'917832128',invoice:'1460254888',note:'936516620',advance:'592906968'};
function validDate(y,m,d){y=Number(y);m=Number(m);d=Number(d);if(y>=1&&y<=199)y+=1911;else if(y<1912||y>2500)return '';const date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d?`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`:'';}
function money(x){const s=String(x??'').replace(/[,，\s$＄元NTD]/g,'');return /^\d+(?:\.\d{1,2})?$/.test(s)?Number(s):null;}
function parse(raw){
 const t=String(raw||'').normalize('NFKC'),lines=t.split(/[\r\n]+/).map(l=>l.replace(/\s+/g,' ').replace(/(?<=[\u3400-\u9fff]) (?=[\u3400-\u9fff])/g,'').trim()).filter(Boolean),flat=lines.join('').replace(/\s/g,''),out={warnings:[]};
 const postal=/購買[票栗]品[證証]明單|forPostageStamp/i.test(flat),receipt=postal||/免用統一發票收[據据]|免用統一發票收擀/.test(flat)||(/收[據据]/.test(flat)&&!/(?:電子發票|統一發票證明)/.test(flat));
 out.document=receipt?'receipt':undefined;
 const invoiceValues=[];let lineNo=0;for(const line of t.toUpperCase().split(/[\r\n]+/)){lineNo++;const code='([A-Z]{2})[ \-]*(\\d(?:[ \-]*\\d){7})(?!\\d)';const labeled=line.match(new RegExp('(?:發票(?:號碼|號)|票號)\\s*[:：]?\\s*'+code));const bare=line.match(new RegExp('^[ \,|_:.]*'+code+'\\s*$'));const header=lineNo<=14&&!/買方|賣方|統一編號|隨機|店.*序/.test(line)?line.match(new RegExp('^[^:：]{1,10}[:：]\\s*'+code)):null;const m=labeled||bare||header;if(m)invoiceValues.push(m[1]+m[2].replace(/[ \-]/g,''));}const invoices=[...new Set(invoiceValues)];
 if(!receipt){if(invoices.length===1)out.invoice=invoices[0];else out.warnings.push(invoices.length?'找到多個發票號碼，請確認。':'未辨識到發票號碼，請手填或改辨識上半部。');}
 const dateText=lines.filter(line=>!/截止|兌換|換開|有效期限|有效日期|換開發票/.test(line)).join('\n').replace(/\d{3,4}\s*年\s*\d{1,2}\s*[-–—]\s*\d{1,2}\s*月?/g,'');
 const dates=[...new Set([...dateText.matchAll(/(?<!\d)(\d{2,4})\s*[年./-]\s*(\d{1,2})\s*[月./-]\s*(\d{1,2})(?!\d)/g)].map(m=>validDate(m[1],m[2],m[3])).filter(Boolean))];
 if(dates.length===1)out.date=dates[0];else out.warnings.push(dates.length?'找到多個日期，請確認開票日。':'未辨識到有效日期，請手填；異常年份不自動帶入。');
 // Values must follow a recognized label, on the same line or a purely numeric next line.
 function valuesFor(pattern,kind){const found=[];for(let i=0;i<lines.length;i++){const line=lines[i].replace(/^[|\-:：_]+\s*/,'');if(/新[臺台]幣.*中文|大寫/.test(line))continue;const m=line.match(pattern);if(!m)continue;let tail=line.slice(m.index+m[0].length).trim().replace(/^[:：]\s*/,'');
 if(kind==='tax'&&/^營業稅/.test(line)){const box=tail.match(/免稅\s*(\d[\d,]*(?:\.\d{1,2})?)(?:\s|$|[^\d])/);if(box){const n=money(box[1]);if(n!==null)found.push(n);continue;}}
 let v=tail.match(/^(?:NT\$|NTD|[$＄])?\s*(\d[\d,]*(?:\.\d{1,2})?)(?=元|\s|$|[^\d])/i);
 if(v&&kind==='total'){const rest=tail.slice(v[0].length).trim();if(/^\d[\d,]*(?:\.\d{1,2})?(?:元)?$/.test(rest)){const n=money(rest);if(n!==null){found.push(n);continue;}}}
 if(!v&&/^[^0-9]*$/.test(tail)&&i+1<lines.length)v=lines[i+1].match(/^(?:NT[:：]?|NT\$|NTD|[$＄])?\s*(\d[\d,]*(?:\.\d{1,2})?)(?:\s*元整?|\s*統一編號[:：].*)?$/i);
 if(v){const n=money(v[1]);if(n!==null)found.push(n);}}return [...new Set(found)];}
 const amounts={expense:valuesFor(/(?:未稅(?:金額|總額)?|(?:應稅|應税)?(?:銷售|銷貨|销售|銷售)額(?:合計|台計)?|^SUBTOTAL)/i,'expense'),tax:valuesFor(/(?:^營業稅(?:應稅[✓√\/]*零稅率免稅)?|^稅[額额癌#]|^稅金|^稅(?=[:：\d$])|^TAX(?:AMOUNT)?)/i,'tax'),total:valuesFor(/(?:含稅(?:總額|金額)?|總計|總金額|總額|總價|合計金額|應付金額|^TOTAL(?:AMOUNT)?|GRANDTOTAL)/i,'total')};
 for(const k of Object.keys(amounts)){out[k]=amounts[k].length===1?amounts[k][0]:null;if(amounts[k].length>1)out.warnings.push('找到不同的'+({expense:'未稅金額',tax:'稅額',total:'總額'})[k]+'，請確認。');}
 if(postal&&out.total===null){const nt=[...t.matchAll(/(?:NT[:：]\s*|NT\$\s*)(\d[\d,]*(?:\.\d{1,2})?)/gi)].map(m=>money(m[1])).filter(v=>v!==null&&v>0);const unique=[...new Set(nt)];if(unique.length===1)out.total=unique[0];}
 const explicitNoTax=/免用統一發票收[據据]/.test(flat)||(postal&&/免稅/.test(flat));
 if(receipt&&explicitNoTax&&out.total!==null&&out.tax===null){out.tax=0;out.expense=out.total;out.warnings.push('依憑證免稅／免用發票文字帶入稅額 0，請核對。');}
 if(out.expense===null&&out.total!==null&&out.tax!==null&&out.total>=out.tax){out.expense=Math.round((out.total-out.tax)*100)/100;out.warnings.push('未稅金額由總額減已辨識稅額帶入，請核對。');}
 if(out.total===null&&out.expense!==null&&out.tax!==null)out.total=Math.round((out.expense+out.tax)*100)/100;
 if(out.expense!==null&&out.tax!==null&&out.total!==null&&Math.abs(out.expense+out.tax-out.total)>0.005){out.warnings.push('辨識金額不平衡，請勿直接送出。');}
 if(out.expense===null||out.tax===null||out.total===null)out.warnings.push('金額尚未完整；可改辨識金額區、貼上手機辨識文字或手填。不猜 5% 稅額。');
 return out;
}
function mergePasses(texts){const parsed=texts.map(parse),out={warnings:[]};for(const key of ['date','invoice','expense','tax','total','document']){const vals=[...new Set(parsed.map(p=>p[key]).filter(v=>v!==undefined&&v!==null))];if(vals.length===1)out[key]=vals[0];else if(vals.length>1)out.warnings.push('不同辨識結果對 '+({date:'日期',invoice:'發票號碼',expense:'支出',tax:'稅額',total:'總額',document:'憑證種類'})[key]+' 有衝突，請手填。');}if(out.document==='receipt'){delete out.invoice;const all=texts.join('').replace(/\s/g,'');if(out.total>0&&out.tax===undefined&&(/免用統一發票收[據据]/.test(all)||(/購買[票栗]品[證証]明單|forPostageStamp/i.test(all)&&/免稅/.test(all)))){out.tax=0;out.expense=out.total;out.warnings.push('依憑證免稅／免用發票文字帶入稅額 0，請核對。');}}if(out.expense!==undefined&&out.tax!==undefined&&out.total!==undefined&&Math.abs(out.expense+out.tax-out.total)>0.005){delete out.expense;delete out.tax;delete out.total;out.warnings.push('不同區域金額不平衡，已留空請核對。');}if(!out.date)out.warnings.push('日期未辨識，請填有效開票日。');if(out.document!=='receipt'&&!out.invoice)out.warnings.push('發票號碼未辨識，請確認。');if(out.expense===undefined||out.tax===undefined||out.total===undefined)out.warnings.push('金額未完整，請核對缺少欄位。');return out;}
function metadata(v,id){const fields=[`【收支類型:${v.direction==='income'?'收入':'支出'}】`,`【憑證ID:${id}】`,`【憑證種類:${v.document==='receipt'?'收據':v.document==='pending'?'未開發票':'發票'}】`,`【總額:${v.total}】`];if(v.paymentDate)fields.push(`【收付日:${v.paymentDate}】`);return [String(v.note||'').replace(/【(?:憑證ID|憑證種類|總額|付款日|收付日|收支類型):[^】]*】/g,'').trim(),fields.join('')].filter(Boolean).join('\n');}
function payload(v,id){const data={...v,expense:v.direction==='income'?'':v.expense,income:v.direction==='income'?v.total:'',invoice:v.document==='receipt'?'收據':v.document==='pending'?'未開發票':String(v.invoice||'').toUpperCase().replace(/\s|-/g,''),note:metadata(v,id)};const p=new URLSearchParams();for(const k of Object.keys(ENTRY))p.append('entry.'+ENTRY[k],data[k]||data[k]===0?String(data[k]):'');return p;}
function validate(v){const e=[],income=v.direction==='income',paid=income?'V':'C';if(!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||validDate(...v.date.split('-'))!==v.date)e.push('請填有效日期');if(!['invoice','receipt','pending'].includes(v.document))e.push('請選憑證種類');if(v.document==='invoice'&&!/^[A-Z]{2}\d{8}$/.test(String(v.invoice).toUpperCase().replace(/[\s-]/g,'')))e.push('發票號碼需為 2 個英文字母＋8 位數字');const a=money(v.expense),b=money(v.tax),c=money(v.total);if(b===null||c===null||c<=0||(!income&&a===null))e.push('請填金額、稅額與總額');else if(income?b>c:Math.abs(a+b-c)>0.005)e.push(income?'稅額不可大於含稅收入':'支出＋稅額與總額不符');if(!['',paid].includes(v.payment))e.push(income?'收入只能選 V 收訖或空白':'支出只能選 C 付訖或空白');if(v.payment===paid&&!v.paymentDate)e.push('收付訖請填實際收付日');if(v.paymentDate&&validDate(...v.paymentDate.split('-'))!==v.paymentDate)e.push('收付日格式不正確');if(v.payment===''&&v.paymentDate)e.push('未收付請清空實際收付日');if(!['','潘','黃','張','吳','lab'].includes(v.advance))e.push('請選單一代收墊');if(!String(v.item||'').trim())e.push('請填項目');if(!String(v.currency||'').trim())e.push('請填幣別');return e;}
function applyRules(raw,rules,current={}){const candidates={},warnings=[],text=(String(raw).normalize('NFKC').replace(/\s/g,'').replace(/購買栗品[證証]明單/g,'購買票品證明單')+(/forPostageStamp/i.test(String(raw).replace(/\s/g,''))?'購買票品證明單':'')).toLowerCase();for(const r of rules){if(!r.keyword||!r.value||!['item','person','currency','note'].includes(r.field))continue;if(text.includes(String(r.keyword).normalize('NFKC').replace(/\s/g,'').toLowerCase()))(candidates[r.field]??=[]).push(String(r.value));}const values={};for(const [field,list] of Object.entries(candidates)){if(String(current[field]||'').trim())continue;const unique=[...new Set(list)];if(unique.length===1)values[field]=unique[0];else warnings.push('多條規則對「'+field+'」給出不同內容，請手動確認。');}return {values,warnings};}
const api={FORM,ENTRY,parse,mergePasses,payload,validate,applyRules,validDate,money};global.ReceiptParser=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
